services:
  - type: web
    name: sfss
    runtime: docker
    dockerfilePath: ./Dockerfile
    envVars:
      - key: SPRING_PROFILE
        value: prod
      - key: DATABASE_URL
        sync: false
      - key: DATABASE_USERNAME
        sync: false
      - key: DATABASE_PASSWORD
        sync: false
      - key: SUPABASE_STORAGE_URL
        sync: false
      - key: SUPABASE_STORAGE_ACCESS_KEY
        sync: false
      - key: SUPABASE_STORAGE_SECRET_KEY
        sync: false
      - key: SUPABASE_STORAGE_BUCKET
        sync: false