spring.datasource.url=jdbc:postgresql://localhost:5432/sfss_db
spring.datasource.username=postgres
#spring.datasource.password=admin123
spring.datasource.password=Etr!gancod1

file.upload-dir=D:/Project/SFSS/uploads