#spring.datasource.url=jdbc:postgresql://localhost:5432/sfss_db
#spring.datasource.username=postgres
##spring.datasource.password=admin123
#spring.datasource.password=Etr!gancod1
#
#file.upload-dir=D:/Project/SFSS/uploads



spring.datasource.url=jdbc:postgresql://localhost:5432/sfss_db
spring.datasource.username=postgres
#spring.datasource.password=admin123
spring.datasource.password=Etr!gancod1
file.upload-dir=D:/Project/SFSS/uploads

spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true
spring.jpa.properties.hibernate.boot.allow_jdbc_metadata_access=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

supabase.storage.url=https://wridsdirgmjxwlnszyvp.supabase.co/storage/v1/s3
supabase.storage.access-key=509319fc2326a19c47597620b4c7a895
supabase.storage.secret-key=a3a5d651a6783507630f28c8326666404fe04f0ffc176d80d177da0678358e4a
supabase.storage.bucket=sfss-files
supabase.storage.region=ap-south-1

openai.api.key=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