#spring.datasource.url=jdbc:postgresql://aws-1-ap-south-1.pooler.supabase.com:6543/postgres?sslmode=require&pgbouncer=true&prepareThreshold=0
#spring.datasource.username=postgres.wridsdirgmjxwlnszyvp
#spring.datasource.password=Etr!gancod1
#file.upload-dir=D:/Project/SFSS/uploads
#
#spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true
#spring.jpa.properties.hibernate.boot.allow_jdbc_metadata_access=false
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
#spring.datasource.hikari.connection-timeout=30000
#spring.datasource.hikari.maximum-pool-size=5

#supabase.storage.url=supabase.storage.url=https://wridsdirgmjxwlnszyvp.supabase.co
#supabase.storage.url=https://wridsdirgmjxwlnszyvp.supabase.co
supabase.storage.url=${SUPABASE_STORAGE_URL}
SUPABASE_STORAGE_URL="https://wridsdirgmjxwlnszyvp.supabase.co
#supabase.storage.key=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndyaWRzZGlyZ21qeHdsbnN6eXZwIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc3NjQzOTg3NSwiZXhwIjoyMDkyMDE1ODc1fQ.mNt-hujDTf4CSMghUONsYx_IjOzSaD9n3I2ehnmVPCI

supabase.storage.access-key=509319fc2326a19c47597620b4c7a895
supabase.storage.secret-key=a3a5d651a6783507630f28c8326666404fe04f0ffc176d80d177da0678358e4a
supabase.storage.bucket=sfss-files

supabase.storage.region=ap-south-1

spring.datasource.url=${DATABASE_URL}
spring.datasource.username=${DATABASE_USERNAME}
spring.datasource.password=${DATABASE_PASSWORD}
file.upload-dir=${UPLOAD_DIR:/tmp/uploads}

spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true
spring.jpa.properties.hibernate.boot.allow_jdbc_metadata_access=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.datasource.hikari.connection-timeout=30000
spring.datasource.hikari.maximum-pool-size=3